version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/maven-multi-module"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
  - package-ecosystem: "maven"
    directory: "/maven-multi-module/template-domain"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/maven-multi-module/template-adapter-inbound"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/maven-multi-module/template-adapter-outbound"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/maven-multi-module/template-view-model"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/maven-multi-module/template-client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/maven-multi-module/template"
    schedule:
      interval: "weekly"
